name: Deploy Flutter Web App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24
          channel: stable

      - name: Blue Fire Team Actions
        uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /useful-app/
          webRenderer: canvaskit
